# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: a45d46e8b7004c13e549ce177ccdd56bcb197bbfdd27b8ddfb918c82f6dac61f4315ceefc8df5422005aa6338d13d6dfa9d9dba7d9bdec50560f1c1ea8b495d6

test:
  secret_key_base: 10a63bf2f2e1642e520f3f6c492df06ad3668aea7b3780f344b9c6d24361bd5b7a413c7012df6eb99486d0ec710f63995b6ca41eca0d8f595458368b65ac7306

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
